<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup>
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>

	
	<ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="Stimulsoft.Reports.Web.NetCore" Version="2024.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data\Data.csproj" />
    <ProjectReference Include="..\ReportBuilder.Entities\RB.Entities.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Aspose.Cells">
      <HintPath>..\ExteraAssembiles\Aspose.Cells.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
