using System.ComponentModel.DataAnnotations;

namespace Entities.App.Inv.Enums
{
	public enum PartDataSheetEnum
	{
		[Display(Name = "Air-end")]
		Airend = 637,
		[Display(Name = "Electro Motor")]
		Electro_Motor = 638,
		[Display(Name = "Cooling Fan")]
		Cooling_Fan = 639,
		[Display(Name = "Unloader Valve")]
		Unloader_Valve = 640,
		[Display(Name = "Minimum Pressure Valve")]
		Minimum_Pressure_Valve = 641,
		[Display(Name = "Oil Termostatic Valve")]
		Oil_Termostatic_Valve = 642,
		[Display(Name = "Air/Oil Filter Seprator")]
		AirOil_Filter_Seprator = 643,
		[Display(Name = "Air Intake Filter")]
		Air_Intake_Filter = 644,
		[Display(Name = "Temprature Sensor")]
		Temprature_Sensor = 645,
		[Display(Name = "Pressure Sensor")]
		Pressure_Sensor = 646,
		[Display(Name = "Pressure Gauge")]
		Pressure_Gauge = 647,
		[Display(Name = "Pressure Safety Valve")]
		Pressure_Safety_Valve = 648,
		[Display(Name = "Coupling / Pulley")]
		Coupling__Pulley = 649,
		[Display(Name = "Cooler Model")]
		Cooler_Model = 650,
		[Display(Name = "Oil Filter")]
		Oil_Filter = 651,
		[Display(Name = "Belt Size")]
		Belt_Size = 652,
		[Display(Name = "Oil Capacity")]
		Oil_Capacity = 653,
		[Display(Name = "Control Board Type")]
		Control_Board_Type = 715,
		[Display(Name = "Desiccant Type 1")]
		Desiccant_Type_1 = 716,
		[Display(Name = "Desiccant Type 2")]
		Desiccant_Type_2 = 717,
		[Display(Name = "Ceramic Ball Type")]
		Ceramic_Ball_Type = 718,
		[Display(Name = "Pressure Switch")]
		Pressure_Switch = 719,
		[Display(Name = "Silencer")]
		Silencer = 721,
		[Display(Name = "Ball Valve")]
		Ball_Valve = 722,
		[Display(Name = "Check Valve")]
		Check_Valve = 723,
		[Display(Name = "Shuttle Valve")]
		Shuttle_Valve = 724,
		[Display(Name = "Heater")]
		Heater = 725,
		[Display(Name = "Regeneration Valve")]
		Regeneration_Valve = 726,
		[Display(Name = "Adjusting Purge Valve Type")]
		Adjusting_Purge_Valve_Type = 727,
		[Display(Name = "Tempreture Transmitter")]
		Tempreture_Transmitter = 728,
		[Display(Name = "Blower")]
		Blower = 729,
		[Display(Name = "VIP Valve 3/8")]
		VIP_Valve_38 = 789,
		[Display(Name = "VIP Valve 1/2")]
		VIP_Valve_12 = 790,
		[Display(Name = "VIP Valve 3/4")]
		VIP_Valve_34 = 791,
		[Display(Name = "VIP Valve 1")]
		VIP_Valve_1 = 792,
		[Display(Name = "VIP Valve 1-1/4")]
		VIP_Valve_114 = 793,
		[Display(Name = "VIP Valve 1-1/2")]
		VIP_Valve_112 = 794,
		[Display(Name = "Angle Seat Valve")]
		Angle_Seat_Valve = 795,
		[Display(Name = "Adsorber Type (Kg)")]
		Adsorber_Type_Kg = 798,
		[Display(Name = "Ceramic Ball Type 2")]
		Ceramic_Ball_Type_2 = 800,
		[Display(Name = "Coconut Top of Adsorbers")]
		Coconut_Top_of_Adsorbers = 801,
		[Display(Name = "Pressure Indicator")]
		Pressure_Indicator = 804,
		[Display(Name = "Oxygen Analyzer")]
		Oxygen_Analyzer = 805,
		[Display(Name = "HDM Valve Block")]
		HDM_Valve_Block = 806,
		[Display(Name = "Flowmeter")]
		Flowmeter = 807,
		[Display(Name = "Diffuser")]
		Diffuser = 808,
		[Display(Name = "Butterfly Valve")]
		Butterfly_Valve = 922,
		[Display(Name = "Angle Seat Valve2")]
		Angle_Seat_Valve2 = 923,
		[Display(Name = "Ball Valve 1/2 inch")]
		Ball_Valve_12_inch = 1230,
		[Display(Name = "Ball Valve 3/4 inch")]
		Ball_Valve_34_inch = 1231,
		[Display(Name = "Ball Valve 1 inch")]
		Ball_Valve_1_inch = 1232,
		[Display(Name = "Ball Valve 1.1/4 inch")]
		Ball_Valve_114_inch = 1233,
		[Display(Name = "Ball Valve 1.1/2 inch")]
		Ball_Valve_112_inch = 1234,
		[Display(Name = "Ball Valve 2 inch")]
		Ball_Valve_2_inch = 1235,
		[Display(Name = "Ball Valve 2.1/2 inch")]
		Ball_Valve_212_inch = 1236,
		[Display(Name = "Ball Valve 3 inch")]
		Ball_Valve_3_inch = 1237,
		[Display(Name = "Ball Valve 4 inch")]
		Ball_Valve_4_inch = 1238,
		[Display(Name = "Ball Valve 5 inch")]
		Ball_Valve_5_inch = 1239,
		[Display(Name = "Angle Seat Valve 1/2 inch")]
		Angle_Seat_Valve_12_inch = 1240,
		[Display(Name = "Angle Seat Valve 3/4 inch")]
		Angle_Seat_Valve_34_inch = 1241,
		[Display(Name = "Angle Seat Valve 1 inch")]
		Angle_Seat_Valve_1_inch = 1242,
		[Display(Name = "Angle Seat Valve 1.1/4 inch")]
		Angle_Seat_Valve_114_inch = 1243,
		[Display(Name = "Angle Seat Valve 1.1/2 inch")]
		Angle_Seat_Valve_112_inch = 1244,
		[Display(Name = "Angle Seat Valve 2 inch")]
		Angle_Seat_Valve_2_inch = 1245,
		[Display(Name = "Angle Seat Valve 2.1/2 inch")]
		Angle_Seat_Valve_212_inch = 1246,
		[Display(Name = "Angle Seat Valve 3 inch")]
		Angle_Seat_Valve_3_inch = 1247,
		[Display(Name = "Angle Seat Valve 4 inch")]
		Angle_Seat_Valve_4_inch = 1248,
		[Display(Name = "Angle Seat Valve 5 inch")]
		Angle_Seat_Valve_5_inch = 1249,
		[Display(Name = "Butterfly Valve 1/2 inch")]
		Butterfly_Valve_12_inch = 1250,
		[Display(Name = "Butterfly Valve 3/4 inch")]
		Butterfly_Valve_34_inch = 1251,
		[Display(Name = "Butterfly Valve 1 inch")]
		Butterfly_Valve_1_inch = 1252,
		[Display(Name = "Butterfly Valve 1.1/4 inch")]
		Butterfly_Valve_114_inch = 1253,
		[Display(Name = "Butterfly Valve 1.1/2 inch")]
		Butterfly_Valve_112_inch = 1254,
		[Display(Name = "Butterfly Valve 2 inch")]
		Butterfly_Valve_2_inch = 1255,
		[Display(Name = "Butterfly Valve 2.1/2 inch")]
		Butterfly_Valve_212_inch = 1256,
		[Display(Name = "Butterfly Valve 3 inch")]
		Butterfly_Valve_3_inch = 1257,
		[Display(Name = "Butterfly Valve 4 inch")]
		Butterfly_Valve_4_inch = 1258,
		[Display(Name = "Butterfly Valve 5 inch")]
		Butterfly_Valve_5_inch = 1259,
		[Display(Name = "Shuttle Valve 1/2 inch")]
		Shuttle_Valve_12_inch = 1260,
		[Display(Name = "Shuttle Valve 3/4 inch")]
		Shuttle_Valve_34_inch = 1261,
		[Display(Name = "Shuttle Valve 1 inch")]
		Shuttle_Valve_1_inch = 1262,
		[Display(Name = "Shuttle Valve 1.1/4 inch")]
		Shuttle_Valve_114_inch = 1263,
		[Display(Name = "Shuttle Valve 1.1/2 inch")]
		Shuttle_Valve_112_inch = 1264,
		[Display(Name = "Shuttle Valve 2 inch")]
		Shuttle_Valve_2_inch = 1265,
		[Display(Name = "Shuttle Valve 2.1/2 inch")]
		Shuttle_Valve_212_inch = 1266,
		[Display(Name = "Shuttle Valve 3 inch")]
		Shuttle_Valve_3_inch = 1267,
		[Display(Name = "Shuttle Valve 4 inch")]
		Shuttle_Valve_4_inch = 1268,
		[Display(Name = "Shuttle Valve 5 inch")]
		Shuttle_Valve_5_inch = 1269,
		[Display(Name = "Pressure Safety Valve 1/2 inch")]
		Pressure_Safety_Valve_12_inch = 1270,
		[Display(Name = "Pressure Safety Valve 3/4 inch")]
		Pressure_Safety_Valve_34_inch = 1271,
		[Display(Name = "Pressure Safety Valve 1 inch")]
		Pressure_Safety_Valve_1_inch = 1272,
		[Display(Name = "Pressure Safety Valve 1.1/4 inch")]
		Pressure_Safety_Valve_114_inch = 1273,
		[Display(Name = "Pressure Safety Valve 1.1/2 inch")]
		Pressure_Safety_Valve_112_inch = 1274,
		[Display(Name = "Pressure Safety Valve 2 inch")]
		Pressure_Safety_Valve_2_inch = 1275,
		[Display(Name = "Pressure Safety Valve 2.1/2 inch")]
		Pressure_Safety_Valve_212_inch = 1276,
		[Display(Name = "Pressure Safety Valve 3 inch")]
		Pressure_Safety_Valve_3_inch = 1277,
		[Display(Name = "Pressure Safety Valve 4 inch")]
		Pressure_Safety_Valve_4_inch = 1278,
		[Display(Name = "Pressure Safety Valve 5 inch")]
		Pressure_Safety_Valve_5_inch = 1279,
		[Display(Name = "Check Valve 1/2 inch")]
		Check_Valve_12_inch = 1280,
		[Display(Name = "Check Valve 3/4 inch")]
		Check_Valve_34_inch = 1281,
		[Display(Name = "Check Valve 1 inch")]
		Check_Valve_1_inch = 1282,
		[Display(Name = "Check Valve 1.1/4 inch")]
		Check_Valve_114_inch = 1283,
		[Display(Name = "Check Valve 1.1/2 inch")]
		Check_Valve_112_inch = 1284,
		[Display(Name = "Check Valve 2 inch")]
		Check_Valve_2_inch = 1285,
		[Display(Name = "Check Valve 2.1/2 inch")]
		Check_Valve_212_inch = 1286,
		[Display(Name = "Check Valve 3 inch")]
		Check_Valve_3_inch = 1287,
		[Display(Name = "Check Valve 4 inch")]
		Check_Valve_4_inch = 1288,
		[Display(Name = "Check Valve 5 inch")]
		Check_Valve_5_inch = 1289,
		[Display(Name = "Angle Seat Valve 1.1/2 inch2")]
		Angle_Seat_Valve_112_inch2 = 2789,
		[Display(Name = "Angle Seat Valve 6 inch")]
		Angle_Seat_Valve_6_inch = 2904,
		[Display(Name = "Angle Seat Valve 8 inch")]
		Angle_Seat_Valve_8_inch = 2905,
		[Display(Name = "Angle Seat Valve 10 inch")]
		Angle_Seat_Valve_10_inch = 2906,
		[Display(Name = "Ball Valve 6 inch")]
		Ball_Valve_6_inch = 2907,
		[Display(Name = "Ball Valve 8 inch")]
		Ball_Valve_8_inch = 2908,
		[Display(Name = "Ball Valve 10 inch")]
		Ball_Valve_10_inch = 2909,
		[Display(Name = "Butterfly Valve 6 inch")]
		Butterfly_Valve_6_inch = 2910,
		[Display(Name = "Butterfly Valve 8 inch")]
		Butterfly_Valve_8_inch = 2911,
		[Display(Name = "Butterfly Valve 10 inch")]
		Butterfly_Valve_10_inch = 2912,
		[Display(Name = "Shuttle Valve 6 inch")]
		Shuttle_Valve_6_inch = 2913,
		[Display(Name = "Shuttle Valve 8 inch")]
		Shuttle_Valve_8_inch = 2914,
		[Display(Name = "Shuttle Valve 10 inch")]
		Shuttle_Valve_10_inch = 2915,
		[Display(Name = "Pressure Safety Valve 6 inch")]
		Pressure_Safety_Valve_6_inch = 2916,
		[Display(Name = "Pressure Safety Valve 8 inch")]
		Pressure_Safety_Valve_8_inch = 2917,
		[Display(Name = "Pressure Safety Valve 10 inch")]
		Pressure_Safety_Valve_10_inch = 2918,
		[Display(Name = "Check Valve 6 inch")]
		Check_Valve_6_inch = 2919,
		[Display(Name = "Check Valve 8 inch")]
		Check_Valve_8_inch = 2920,
		[Display(Name = "Check Valve 10 inch")]
		Check_Valve_10_inch = 2921,
	}
}
