<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\css\**" />
    <Compile Remove="wwwroot\js\**" />
    <Content Remove="wwwroot\css\**" />
    <Content Remove="wwwroot\js\**" />
    <EmbeddedResource Remove="wwwroot\css\**" />
    <EmbeddedResource Remove="wwwroot\js\**" />
    <None Remove="wwwroot\css\**" />
    <None Remove="wwwroot\js\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
    <PackageReference Include="Stimulsoft.Reports.Web.NetCore" Version="2024.3.2" />
  </ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportBuilder.Services\RB.Services.csproj" />
    <ProjectReference Include="..\WebFramework\WebFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Aspose.Cells">
      <HintPath>..\ExteraAssembiles\Aspose.Cells.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
