using Common;
using Common.Attributes;
using Common.Utilities;
using Data.Contracts;
using Entities.Base;
using Entities.Base.FormBuilder;
using Entities.Base.System;
using Entities.Base.System.Enums;
using Microsoft.EntityFrameworkCore;

namespace Data.Services;

public interface IPageBuilderService
{
	Task<PageDefinition?> GetByIdAsync(long id, CancellationToken cancellationToken = default);
	Task<PageDefinition?> GetByPathAsync(string viewPath, CancellationToken cancellationToken = default);
	Task<PageDefinition> CreateAsync(PageDefinition page, CancellationToken cancellationToken = default);
	Task<PageDefinition> UpdateAsync(PageDefinition page, CancellationToken cancellationToken = default);
	Task DeleteAsync(long id, CancellationToken cancellationToken = default);
	Task EnsureFormPagesAsync(FormDefinition formDefinition, FormPageContent? content = null, CancellationToken cancellationToken = default);
	Task RemoveFormPagesAsync(long formDefinitionId, CancellationToken cancellationToken = default);
	Task WarmCacheAsync(CancellationToken cancellationToken = default);
}

public sealed class FormPageContent
{
	public string? ListContent { get; init; }
	public string? EditContent { get; init; }
}

public sealed class PageBuilderService(
	ApplicationDbContext dbContext,
	IUnitOfWork unitOfWork,
	IPageBuilderCache cache) : IPageBuilderService, IScopedDependency
{
	private const string FormBuilderStubContent = "@* Generated by FormBuilder - publish to update content *@\r\n<div class=\"alert alert-info\">صفحه در انتظار انتشار فرم</div>";

	public async Task<PageDefinition?> GetByIdAsync(long id, CancellationToken cancellationToken = default)
	{
		return await unitOfWork.Repository<PageDefinition>()
			.TableNoTracking
			.FirstOrDefaultAsync(p => p.Id == id, cancellationToken);
	}

	public async Task<PageDefinition?> GetByPathAsync(string viewPath, CancellationToken cancellationToken = default)
	{
		var normalized = PageBuilderPathHelper.NormalizeViewPath(viewPath);
		return await unitOfWork.Repository<PageDefinition>()
			.TableNoTracking
			.FirstOrDefaultAsync(p => p.ViewPath == normalized && p.IsActive == IsActiveEnum.Active, cancellationToken);
	}

	public async Task<PageDefinition> CreateAsync(PageDefinition page, CancellationToken cancellationToken = default)
	{
		page.ViewPath = PageBuilderPathHelper.NormalizeViewPath(page.ViewPath);
		page.Version = 1;
		page.SourceType = PageSourceTypeEnum.Manual;
		var saved = await unitOfWork.Repository<PageDefinition>().SaveAsync(page, cancellationToken, true);
		RefreshCacheEntry(saved);
		return saved;
	}

	public async Task<PageDefinition> UpdateAsync(PageDefinition page, CancellationToken cancellationToken = default)
	{
		var existing = await unitOfWork.Repository<PageDefinition>()
			.Table
			.FirstOrDefaultAsync(p => p.Id == page.Id, cancellationToken)
			?? throw new InvalidOperationException("صفحه یافت نشد");

		if (existing.SourceType == PageSourceTypeEnum.FormBuilder)
			page.ViewPath = existing.ViewPath;
		else
			page.ViewPath = PageBuilderPathHelper.NormalizeViewPath(page.ViewPath);

		existing.DisplayName = page.DisplayName;
		existing.Content = page.Content ?? string.Empty;
		existing.PageKind = page.PageKind;
		existing.Module = page.Module;
		if (existing.SourceType == PageSourceTypeEnum.Manual)
			existing.ViewPath = page.ViewPath;
		existing.Version += 1;

		await dbContext.SaveChangesAsync(cancellationToken);
		RefreshCacheEntry(existing);
		return existing;
	}

	public async Task DeleteAsync(long id, CancellationToken cancellationToken = default)
	{
		var page = await unitOfWork.Repository<PageDefinition>()
			.Table
			.FirstOrDefaultAsync(p => p.Id == id, cancellationToken);

		if (page == null)
			return;

		page.IsActive = IsActiveEnum.Deleted;
		await dbContext.SaveChangesAsync(cancellationToken);
		cache.Remove(page.ViewPath);
	}

	public async Task EnsureFormPagesAsync(
		FormDefinition formDefinition,
		FormPageContent? content = null,
		CancellationToken cancellationToken = default)
	{
		if (formDefinition.Id == null)
			return;

		var (listPath, editPath) = PageBuilderPathHelper.GetStandardFormViewPaths(
			formDefinition.Module,
			formDefinition.EntityName);

		await UpsertFormPageAsync(
			formDefinition,
			listPath,
			$"لیست {formDefinition.DisplayName}",
			PageKindEnum.List,
			content?.ListContent ?? FormBuilderStubContent,
			cancellationToken);

		await UpsertFormPageAsync(
			formDefinition,
			editPath,
			$"درج/ویرایش {formDefinition.DisplayName}",
			PageKindEnum.Edit,
			content?.EditContent ?? FormBuilderStubContent,
			cancellationToken);
	}

	public async Task RemoveFormPagesAsync(long formDefinitionId, CancellationToken cancellationToken = default)
	{
		var pages = await unitOfWork.Repository<PageDefinition>()
			.Table
			.Where(p => p.FormDefinitionId == formDefinitionId)
			.ToListAsync(cancellationToken);

		foreach (var page in pages)
		{
			page.IsActive = IsActiveEnum.Deleted;
			cache.Remove(page.ViewPath);
		}

		if (pages.Count > 0)
			await dbContext.SaveChangesAsync(cancellationToken);
	}

	public async Task WarmCacheAsync(CancellationToken cancellationToken = default)
	{
		var pages = await unitOfWork.Repository<PageDefinition>()
			.TableNoTracking
			.Where(p => p.IsActive == IsActiveEnum.Active)
			.Select(p => new
			{
				p.ViewPath,
				p.Content,
				LastModified = p.ModifiedDateMiladiDateTime ?? p.CreatedOnMiladiDateTime ?? DateTime.Now
			})
			.ToListAsync(cancellationToken);

		cache.LoadAll(pages.Select(p => (
			PageBuilderPathHelper.NormalizeViewPath(p.ViewPath),
			p.Content ?? string.Empty,
			new DateTimeOffset(p.LastModified))));
	}

	private async Task UpsertFormPageAsync(
		FormDefinition formDefinition,
		string viewPath,
		string displayName,
		PageKindEnum pageKind,
		string content,
		CancellationToken cancellationToken)
	{
		var normalizedPath = PageBuilderPathHelper.NormalizeViewPath(viewPath);
		var existing = await unitOfWork.Repository<PageDefinition>()
			.Table
			.FirstOrDefaultAsync(p => p.ViewPath == normalizedPath, cancellationToken);

		if (existing == null)
		{
			var page = new PageDefinition
			{
				ViewPath = normalizedPath,
				DisplayName = displayName,
				Content = content,
				PageKind = pageKind,
				SourceType = PageSourceTypeEnum.FormBuilder,
				FormDefinitionId = formDefinition.Id,
				Module = formDefinition.Module,
				Version = 1,
				IsActive = IsActiveEnum.Active
			};
			dbContext.Set<PageDefinition>().Add(page);
		}
		else
		{
			existing.DisplayName = displayName;
			existing.PageKind = pageKind;
			existing.FormDefinitionId = formDefinition.Id;
			existing.Module = formDefinition.Module;
			existing.SourceType = PageSourceTypeEnum.FormBuilder;
			existing.IsActive = IsActiveEnum.Active;

			if (!string.IsNullOrWhiteSpace(content) && content != FormBuilderStubContent)
				existing.Content = content;
			else if (string.IsNullOrWhiteSpace(existing.Content))
				existing.Content = content;

			existing.Version += 1;
		}

		await dbContext.SaveChangesAsync(cancellationToken);

		var saved = await unitOfWork.Repository<PageDefinition>()
			.TableNoTracking
			.FirstAsync(p => p.ViewPath == normalizedPath, cancellationToken);

		RefreshCacheEntry(saved);
	}

	private void RefreshCacheEntry(PageDefinition page)
	{
		if (page.IsActive != IsActiveEnum.Active)
		{
			cache.Remove(page.ViewPath);
			return;
		}

		var lastModified = page.ModifiedDateMiladiDateTime ?? page.CreatedOnMiladiDateTime ?? DateTime.Now;
		cache.Set(page.ViewPath, page.Content ?? string.Empty, new DateTimeOffset(lastModified));
	}
}
