<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>72a79d42-ecea-44a6-a8cc-b3811942e9b0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
 
  </PropertyGroup>

	<PropertyGroup>
		<NuGetAudit>false</NuGetAudit>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" Version="4.14.0" />
  </ItemGroup>

	<ItemGroup>


  

		 
		<Compile Remove="wwwroot\panelLib\plugins\global\fonts\**" />

		 
 
		 
 
	 
		<Content Remove="wwwroot\**\*.tmp" />
		<Content Remove="wwwroot\**\*.bak" />
		<Content Remove="wwwroot\**\*~" />
 
		<Content Remove="wwwroot\panelLib\plugins\global\fonts\**" />

 
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\draggable\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\Dropzone\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\inputmask\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\jstree\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\persion-datepicker\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\queryBuilder\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\select2\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\sortable\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\custom\tinymce\**" />
		<EmbeddedResource Remove="wwwroot\panelLib\plugins\global\fonts\**" />
 
		<None Remove="wwwroot\panelLib\plugins\global\fonts\**" />

	</ItemGroup>

	<ItemGroup Condition="'$(Configuration)' == 'Release'">
		<Content Update="wwwroot\lib\**\*">
			 
		</Content>
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportBuilder.WebApp\RB.WebApp.csproj" />
    <ProjectReference Include="..\WebFramework\WebFramework.csproj" />
    <ProjectReference Include="..\Shared\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Framework\File\" />
    <Folder Include="wwwroot\lib\persian-datepicker-element\" />
    <Folder Include="wwwroot\scripts\" />
    <Folder Include="wwwroot\panelLib\plugins\custom\xlsx\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Aspose.Cells">
      <HintPath>ExteraAssembiles\Aspose.Cells.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="QuestPDF">
      <HintPath>ExteraAssembiles\QuestPDF.dll</HintPath>
    </Reference>
  </ItemGroup>
	 
  <ItemGroup>
    <Content Include="AppData\Document-EditAsGroup-ButtonFlow.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\account.dat">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Aspose.Total.NET.lic">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\StimulSoftLicense.Key">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>