<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>72a79d42-ecea-44a6-a8cc-b3811942e9b0</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.1" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportBuilder.WebApp\RB.WebApp.csproj" />
    <ProjectReference Include="..\WebFramework\WebFramework.csproj" />
    <ProjectReference Include="..\Shared\Shared.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\lib\persian-datepicker-element\" />
    <Folder Include="wwwroot\scripts\" />
    <Folder Include="wwwroot\panelLib\plugins\custom\xlsx\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Aspose.Cells">
      <HintPath>ExteraAssembiles\Aspose.Cells.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>
	 
  <ItemGroup>
    <Content Update="wwwroot\account.dat">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\Aspose.Total.NET.lic">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\favicon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\StimulSoftLicense.Key">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
